name: Test CI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Setup Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          echo "CC=clang-20" >> "$GITHUB_ENV"
          echo "CXX=clang++-20" >> "$GITHUB_ENV"

      # NOTE: meson has no dependencies, so --break-system-packages doesn't really break anything!
      - name: Setup meson
        run: |
          pip install meson --break-system-packages

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build gcovr -y --no-install-recommends

      - name: Configure
        run: meson setup build -Dbuildtype=debug -Db_coverage=true -Dtests=true --fatal-meson-warnings

      - name: Run tests
        run: meson test -C build --verbose

      - name: Generate Coverage File
        run: |
          ninja coverage -C build

      - name: Create Coverage Report
        uses: insightsengineering/coverage-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./build/meson-logs/coverage.xml
          threshold: 0.90 # 0-1
          fail: true
          coverage-reduction-failure: true
          # Publish the rendered output as a PR comment
          publish: true
          coverage-summary-title: 'Code Coverage Summary'
          togglable-report: true
          diff: true
          diff-branch: main

      - name: Upload test coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Tests coverage artifacts
          path: |
            ./build/meson-logs/coverage.xml
            ./build/meson-logs/coveragereport/
